spring.application.name=enterprise-platform
spring.data.mongodb.uri=mongodb://localhost:27017/enterprise-platform
server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.example.demo=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
